from __future__ import annotations

import os
from typing import overload

class PosixFath:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, path: os.PathLike[str]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
