from __future__ import annotations

import os

def posix_normalize(arg: os.PathLike[str], /) -> str: ...
def posix_join(*args: os.PathLike[str]) -> str: ...
def posix_root(arg: os.PathLike[str], /) -> str: ...
def posix_name(arg: os.PathLike[str], /) -> str: ...
def posix_parent(arg: os.PathLike[str], /) -> str: ...
def windows_normalize(arg: os.PathLike[str], /) -> str: ...
def windows_join(*args: os.PathLike[str]) -> str: ...
def windows_drive(arg: os.PathLike[str], /) -> str: ...
def windows_root(arg: os.PathLike[str], /) -> str: ...
def windows_name(arg: os.PathLike[str], /) -> str: ...
def windows_parent(arg: os.PathLike[str], /) -> str: ...

class PosixFath:
    def __init__(self, *parts: os.PathLike[str]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class WindowsFath:
    def __init__(self, *parts: os.PathLike[str]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
