from __future__ import annotations

import os

def posix_normalize_slash(inner: str, /) -> str: ...
def posix_normalize_dot(inner: str, /) -> str: ...
def posix_normalize(inner: str, /) -> str: ...
def posix_join(*parts: str) -> str: ...

class PosixFath:
    def __init__(self, *parts: os.PathLike[str]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class WindowsFath:
    def __init__(self, *parts: os.PathLike[str]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
