#ifndef WINDOWS_NORMALIZE_H
#define WINDOWS_NORMALIZE_H

#define PY_SSIZE_T_CLEAN
#include "Python.h"

#include "cow.h"

typedef enum
{
    WINDOWS_NORMALIZE_START,
    WINDOWS_NORMALIZE_START_SLASH,
    WINDOWS_NORMALIZE_START_SLASH_SLASH,
    WINDOWS_NORMALIZE_START_SLASH_SLASH_SLASH,
    WINDOWS_NORMALIZE_START_SLASH_SLASH_SLASH_SLASHES,
    WINDOWS_NORMALIZE_SERVER,
    WINDOWS_NORMALIZE_SERVER_SLASH,
    WINDOWS_NORMALIZE_SERVER_SLASH_SLASHES,
    WINDOWS_NORMALIZE_SHARE,
    WINDOWS_NORMALIZE_SHARE_SLASHES,
    WINDOWS_NORMALIZE_PART,
    WINDOWS_NORMALIZE_PART_SLASHES,
    WINDOWS_NORMALIZE_DOT,
    WINDOWS_NORMALIZE_DOT_SLASHES,
} WindowsNormalize;

int _windows_normalize_impl(Cow *cow, WindowsNormalize *state, PyUnicodeObject *read);
PyUnicodeObject *_windows_normalize(PyUnicodeObject *read);
PyObject *windows_normalize(PyObject *module, PyObject *read);

#endif
